# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_auto_20161103_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationmaintenance',
            old_name='igv_tax',
            new_name='igv_total',
        ),
    ]
