# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_auto_20161103_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationmaintenancedetail',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
