from django.utils.translation import ugettext_lazy as _


# STATUS OF SERVICE CHECKLIST
CODE_SERVICE_MAINTENANCE = '1'
CODE_SERVICE_RENTAL = '2'
SIS_SERVICE_MAINTENANCE_STRING = (CODE_SERVICE_MAINTENANCE, 'Maintenance')
SIS_SERVICE_RENTAL_STRING = (CODE_SERVICE_RENTAL, 'Renta')

STATUS_SERVICE_CHECKLIST_OPTIONS = [
    SIS_SERVICE_MAINTENANCE_STRING, SIS_SERVICE_RENTAL_STRING
]


# STATUS OF ORDER DETAIL
CODE_STATUS_CHECKLIST_PENDING = 'PEND'
CODE_STATUS_CHECKLIST_IN_PROCESS = 'PROCESS'
CODE_STATUS_CHECKLIST_FINISHED = 'FIN'

SIS_STATUS_CHECKLIST_PENDING_STRING = (CODE_STATUS_CHECKLIST_PENDING, 'Pendiente')
SIS_STATUS_CHECKLIST_IN_PROCESS_STRING = (CODE_STATUS_CHECKLIST_IN_PROCESS, 'En Proceso')
SIS_STATUS_CHECKLIST_FINISHED_STRING = (CODE_STATUS_CHECKLIST_FINISHED, 'Finalizado')


STATUS_CHECKLIST_DETAIL_OPTIONS = [
    SIS_STATUS_CHECKLIST_PENDING_STRING, SIS_STATUS_CHECKLIST_IN_PROCESS_STRING,
    SIS_STATUS_CHECKLIST_FINISHED_STRING
]

# TYPE OF CHECKLIST-SOLICITUDE
CODE_CHECKLIST_SOLICITUDE_ENTRY = 'ENTRY'
CODE_CHECKLIST_SOLICITUDE_DEPARTURE = 'DEPT'

SIS_CHECKLIST_SOLICITUDE_ENTRY_STRING = (CODE_CHECKLIST_SOLICITUDE_ENTRY, _('Entry'))
SIS_CHECKLIST_SOLICITUDE_DEPARTURE_STRING = (CODE_CHECKLIST_SOLICITUDE_DEPARTURE, _('Departure'))

TYPE_CHECKLIST_SOLICITUDE_OPTIONS = (
    SIS_CHECKLIST_SOLICITUDE_ENTRY_STRING, SIS_CHECKLIST_SOLICITUDE_DEPARTURE_STRING
)

