# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:24
from __future__ import unicode_literals

import core.utils.upload_folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20161009_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_folder.upload_product_image),
        ),
    ]
