# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20161023_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='logo_product',
        ),
    ]
