# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20161023_1918'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='productsubcategory',
        #     unique_together=set([]),
        # ),
        # migrations.RemoveField(
        #     model_name='productsubcategory',
        #     name='product_category',
        # ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
    ]
