# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20161030_0419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='product_category',
        ),
    ]
