# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20161103_1020'),
        ('taller', '0007_auto_20161103_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSubCategory',
        ),
    ]
