# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160912_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='final_initial_exercise',
            new_name='final_exercise',
        ),
    ]
