# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160916_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='organization/'),
        ),
    ]
