# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160916_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
