# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161021_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfiguration',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
