# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20161021_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmeasurement',
            name='type_measurement',
            field=models.CharField(choices=[('UPM-1', 'Purchase Liquid Unit'), ('UPM-2', 'Purchase Solid Unit'), ('UPM-3', 'Transport Unit'), ('UPM-4', 'Delivery Unit'), ('UPM-5', 'Storage Unit')], max_length=20),
        ),
    ]
