# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20161103_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_handwork_currency', to='core.Currency')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HandWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='handworkcategory',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='handwork',
            name='handwork_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_handwork_handwork_category', to='core.HandWorkCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='handwork',
            unique_together=set([('handwork_category', 'name')]),
        ),
    ]
