# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourchecklist',
            name='status_labour',
            field=models.CharField(blank=True, choices=[('PEND', 'Pendiente'), ('PROCESS', 'En Proceso'), ('FIN', 'Finalizado')], default='PEND', max_length=10, null=True),
        ),
    ]
