# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='taxi_driver_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller_actdeliveryvehicle_taxi_driver_entry', to='core.Person'),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='taxi_driver_exit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller_actdeliveryvehicle_taxi_driver_exit', to='core.Person'),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='type_solicitude_entry',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='type_solicitude_exit',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default=None, max_length=20),
        ),
    ]
