# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_auto_20161027_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='fuel_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller_actdeliveryvehicle_fuel_entry', to='core.VehicleFuel'),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='fuel_exit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller_actdeliveryvehicle_fuel_exit', to='core.VehicleFuel'),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='type_solicitude_entry',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='type_solicitude_exit',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=20),
        ),
    ]
