# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_labourchecklist_status_labour'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourchecklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
