# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_auto_20161027_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdeliveryvehicle',
            name='date_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actdeliveryvehicle',
            name='date_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actdeliveryvehicle',
            name='hour_entry',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AddField(
            model_name='actdeliveryvehicle',
            name='hour_exit',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='actdeliveryvehicle',
            name='following_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
