# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_labourchecklist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourEmployeeCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('is_status', models.BooleanField(default=False)),
                ('labour_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_labouremployeechecklist_labour_checklist', to='taller.LabourCheckList')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionLabourCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_rating', models.CharField(blank=True, max_length=45, null=True)),
                ('checklist_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_supervisionlabourchecklist_checklist_detail', to='taller.CheckListDetail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
