# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_labouremployeechecklist_supervisionlabourchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetail',
            name='fuel_initial',
            field=models.CharField(blank=True, choices=[('1/4', '1/4'), ('1/2', '1/2'), ('full', 'Full')], max_length=200, null=True),
        ),
    ]
