# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20161103_1020'),
        ('vehicle', '0010_auto_20161030_0834'),
        ('core', '0029_auto_20161103_1018'),
        ('taller', '0006_delete_labour'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('code_spt', models.CharField(blank=True, max_length=200, null=True)),
                ('status_requisition', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstore_user', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstore_client', to='core.Person')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionStoreDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_urgent', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstoredetail_product', to='product.Product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstoredetail_product_category', to='product.ProductCategory')),
                ('requisition_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstoredetail_requisition_store', to='taller.RequisitionStore')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_requisitionstoredetail_vehicle', to='vehicle.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('code_wka_maintenance', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignment_user', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignment_vehicle', to='core.Person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignment_vehicle', to='vehicle.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description_labour', models.TextField(blank=True, null=True)),
                ('description_mechanic', models.TextField(blank=True, null=True)),
                ('is_finished_mechanic', models.BooleanField(default=False)),
                ('is_finished_supervisor', models.BooleanField(default=False)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentdetail_labour', to='core.Labour')),
                ('labour_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentdetail_labour_category', to='core.LabourCategory')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentdetail_mechanic', to=settings.AUTH_USER_MODEL)),
                ('work_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentdetail_work_assignment', to='taller.WorkAssignment')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignmentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentstore_product', to='product.Product')),
                ('work_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_workassignmentstore_work_assignment', to='taller.WorkAssignmentDetail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorderstore',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstore',
            name='subsidiary',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstoredetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstoredetail',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstoredetail',
            name='product_subcategory',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstoredetail',
            name='purchase_order_store',
        ),
        migrations.RemoveField(
            model_name='purchaseorderstoredetail',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStore',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStoreDetail',
        ),
    ]
