# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_auto_20160911_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labour',
            name='type_vehicle',
        ),
        migrations.AddField(
            model_name='labour',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='type_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taller_labour_type_job', to='taller.TypeJob'),
            preserve_default=False,
        ),
    ]
