# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_auto_20160914_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
