# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_auto_20160915_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_car',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
