# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_auto_20160915_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status_vehicle',
            field=models.CharField(choices=[('TA1-1', 'Alquilado'), ('TA1-2', 'Mantenimient Income'), ('TA1-3', 'Disponible'), ('TA1-4', 'Null')], default='TA1-3', max_length=10),
        ),
    ]
