# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_auto_20160916_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='labour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taller_quotation_labour', to='taller.Labour'),
            preserve_default=False,
        ),
    ]
