# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='store',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='product_subcategory',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='applicant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='logistic_purchaseorder_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='code_qt_store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
