# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20161019_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='code_qt_store',
            new_name='code_po_store',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='exchange_rate',
        ),
    ]
