# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_purchaseorder_purchase_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
