# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:37
from __future__ import unicode_literals

import core.utils.upload_folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20161013_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_folder.upload_vehicle_image),
        ),
    ]
