# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20161021_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(blank=True, choices=[('', '--Choose--'), ('VHL-1', 'Lightweight'), ('VHL-2', 'Heavy')], max_length=20, null=True),
        ),
    ]
