# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20161023_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='image',
            new_name='logo_vehicle',
        ),
    ]
