# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20161023_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='serie_motor',
            new_name='number_motor',
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='number_serie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='number_vin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
