# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:45
from __future__ import unicode_literals

import core.utils.upload_folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20161023_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_organization',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_folder.upload_organization_image),
        ),
    ]
